{{ if and .Values.agent.enabled (eq .Values.k8sMode "ROSA") }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cloudwatch-agent.name" . }}-scc-role-binding
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:cloudwatch-agent-scc
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "cloudwatch-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:cloudwatch-agent-scc
rules:
  - apiGroups: [""]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]

{{- end }}
