apiVersion: v2
name: amazon-cloudwatch-observability
version: 2.3.1
appVersion: 1.0.0
description: A Helm chart for Amazon CloudWatch Observability
type: application
home: https://aws.amazon.com/cloudwatch/
sources:
  - https://github.com/aws-observability/helm-charts/tree/main/charts/amazon-cloudwatch-observability
maintainers:
  - name: lisaguo
  - name: kausyas
