{{- if .Values.neuronMonitor.enabled }}
apiVersion: cloudwatch.aws.amazon.com/v1alpha1
kind: NeuronMonitor
metadata:
  name: {{ include "neuron-monitor.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ include "neuron-monitor.name" . }}
    version: v1
spec:
  image: {{ template "neuron-monitor.image" . }}
  serviceAccount: {{ template "neuron-monitor.serviceAccountName" . }}
  {{- with .Values.neuronMonitor.nodeSelector }}
  nodeSelector: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.neuronMonitor.affinity }}
  affinity: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.neuronMonitor.resources }}
  resources: {{- toYaml . | nindent 4}}
  {{- end }}
  env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: PATH
    value: /usr/local/bin:/usr/bin:/bin:/opt/aws/neuron/bin
  - name: GOMEMLIMIT
    value: 320MiB
  ports:
  - name: "metrics"
    port: {{ .Values.neuronMonitor.service.port }}
  command:
  - "/bin/bash"
  - "-c"
  - |
    /opt/bin/entrypoint.sh \
      --cert-file /etc/amazon-cloudwatch-observability-neuron-cert/server.crt \
      --key-file /etc/amazon-cloudwatch-observability-neuron-cert/server.key \
      --port {{ .Values.neuronMonitor.service.port }} \
      --neuron-monitor-config /etc/neuron-monitor-config/monitor.json
  securityContext:
    privileged: true
  volumeMounts:
  - mountPath: /etc/amazon-cloudwatch-observability-neuron-cert/
    name: neurontls
    readOnly: true
  - mountPath: /opt-aws
    name: "aws-config"
    readOnly: true
  - mountPath: /neuron-monitor-blocker
    name: neuron-monitor-blocker
    readOnly: true
  volumes:
  - name: neurontls
    secret:
      secretName: amazon-cloudwatch-observability-agent-cert
      items:
        - key: tls.crt
          path: server.crt
        - key: tls.key
          path: server.key
  - name: "aws-config"
    hostPath:
      path: /opt/aws
  - name: neuron-monitor-blocker
    hostPath:
      path: /var/neuron-monitor-blocker
      type: ""
  monitorConfig: |
    {
      "period": "5s",
      "neuron_runtimes": [
        {
          "tag_filter": ".*",
          "metrics": [
            {
              "type": "neuroncore_counters"
            },
            {
              "type": "memory_used"
            },
            {
              "type": "execution_stats"
            }
          ]
        }
      ],
      "system_metrics": [
        {
          "period": "5s",
          "type": "neuron_hw_counters"
        }
      ]
    }
  {{- dict "component" .Values.neuronMonitor "context" . | include "amazon-cloudwatch-observability.common.tolerations" | nindent 2 }}
{{- end }}